const fs=require('fs');let s=fs.readFileSync('index.html','utf8');
const start=s.indexOf('function builder()'); const end=s.indexOf('function bodyweight()');
if(start<0||end<0) throw new Error('anchors missing '+start+' '+end);
const repl = `function builder(){let b=bal(),under=b.filter(x=>x.st==='Under').map(x=>x.m),high=b.filter(x=>x.st==='High').map(x=>x.m);S.builder=S.builder||{goal:'Build muscle',days:4,length:60,focus:'Balanced'};let B=S.builder;let split=adaptiveSplit(B,under,high);window._adaptivePlan=split;let total=split.reduce((a,d)=>a+d.ids.length,0);return H('Adaptive Builder',B.days+' days · '+B.focus)+\`<div class=card><b>Adaptive settings</b><p class=muted>Every setting below changes the preview and the loaded workout.</p><label class=small>Goal</label><div class=tabs>\${['Build muscle','Strength','Recovery','Bodyweight'].map(x=>\`<button class="\${B.goal==x?'sel':''}" onclick="S.builder.goal='\${x}';R()">\${x}</button>\`).join('')}</div><label class=small>Days / week</label><div class=tabs>\${[3,4,5,6].map(x=>\`<button class="\${Number(B.days)==x?'sel':''}" onclick="S.builder.days=\${x};R()">\${x}</button>\`).join('')}</div><label class=small>Session length</label><div class=tabs>\${[30,45,60,75,90].map(x=>\`<button class="\${Number(B.length)==x?'sel':''}" onclick="S.builder.length=\${x};R()">\${x}m</button>\`).join('')}</div><label class=small>Focus</label><div class=tabs>\${['Balanced','Upper','Leg focus','Arms + delts','Weak points','Bodyweight'].map(x=>\`<button class="\${B.focus==x?'sel':''}" onclick="S.builder.focus='\${x}';R()">\${x}</button>\`).join('')}</div><div class=grid2 style="margin-top:12px"><div class=card><div class=muted>Preview days</div><div class=big>\${split.length}</div></div><div class=card><div class=muted>Total moves</div><div class=big>\${total}</div></div></div></div>\`+split.map((d,i)=>\`<div class=card><div class=row><div><b>Day \${i+1}: \${d.name}</b><div class=muted>\${d.note}</div><div class=small>\${d.ids.map(id=>E(id)?.name||id).join(', ')}</div></div><button class=btn onclick="loadAdaptiveDay(\${i})">Load</button></div></div>\`).join('')+\`<div class=grid2><button class=btn onclick="applyAdaptive()">Apply day 1</button><button class="btn btn2" onclick="loadAdaptiveDay(Math.min((S.builder.days||4)-1,(window._adaptivePlan||[]).length-1))">Load last day</button></div>\`}
function adaptiveSplit(B,under=[],high=[]){B=B||{};let days=Number(B.days)||4,len=Number(B.length)||60,goal=B.goal||'Build muscle',focus=B.focus||'Balanced';let slots=len<=30?4:len<=45?5:len<=60?6:len<=75?7:8;let weak=under.includes('Forearms')?'wrist':under.includes('Traps')?'shrug':under.includes('Back')?'lat':under.includes('Legs')?'leg':under.includes('Shoulders')?'latraise':under.includes('Biceps')?'curl':under.includes('Triceps')?'push':'face';let catalog={
upperPush:{name:'Upper Push',ids:['bench','incline','ohp','latraise','push','face','pecdeck','cablelatraise'],note:'Chest, shoulders, triceps.'},
lower:{name:'Leg Focus',ids:['leg','squat','rdl','lunge','legcurl','calf','goblet','hipthrust'],note:'Quads, hamstrings, glutes, calves.'},
upperPull:{name:'Upper Pull',ids:['lat','row','bbrow','curl','hammer','shrug','face','dead_hang'],note:'Back, arms, traps, grip.'},
arms:{name:'Arms + Delts',ids:['latraise','cablelatraise','rearraise','curl','hammer','push','ropepush','wrist'],note:'Delts, biceps, triceps, forearms.'},
full:{name:'Full Body',ids:['bench','lat','leg','ohp','curl','plank','farmer','face'],note:'Balanced whole-body day.'},
weak:{name:'Weak Point Builder',ids:['fly','latraise','push','curl','wrist','shrug',weak,'face'],note:under.length?'Extra: '+under.slice(0,4).join(', '):'Accessory balance.'},
recovery:{name:'Recovery / Mobility',ids:['cat_cow','down_dog','child_pose','world_greatest','easy_seated','box_breathing'],note:'Low fatigue recovery.'},
cardio:{name:'Elliptical + Mobility',ids:['elliptical_easy','cat_cow','child_pose','world_greatest'],note:'Low-impact cardio and movement.'},
body:{name:'Bodyweight Strength',ids:['pushup','invertedrow','airsquat','pikepushup','plank','dead_hang','reverselunge','hollowhold'],note:'No machines or barbell needed.'},
bodyPull:{name:'Bodyweight Pull / Grip',ids:['invertedrow','negativepullup','active_hang','dead_hang','towelrow','bodyweight_row_hold'],note:'Back and grip progression.'},
bodyLegs:{name:'Bodyweight Legs / Core',ids:['airsquat','reverselunge','split_squat_bw','glutebridge','sideplank','hollowhold'],note:'Legs and trunk control.'}
};let order=[];if(goal==='Bodyweight'||focus==='Bodyweight')order=[catalog.body,catalog.bodyLegs,catalog.bodyPull,catalog.body,catalog.bodyLegs,catalog.recovery];else if(goal==='Recovery')order=[catalog.recovery,catalog.cardio,catalog.full,catalog.recovery,catalog.cardio,catalog.body];else if(focus==='Leg focus')order=[catalog.lower,catalog.upperPush,catalog.lower,catalog.upperPull,catalog.lower,catalog.recovery];else if(focus==='Upper')order=[catalog.upperPush,catalog.upperPull,catalog.arms,catalog.upperPush,catalog.full,catalog.recovery];else if(focus==='Arms + delts')order=[catalog.arms,catalog.upperPull,catalog.upperPush,catalog.arms,catalog.full,catalog.recovery];else if(focus==='Weak points')order=[catalog.weak,catalog.upperPush,catalog.lower,catalog.upperPull,catalog.weak,catalog.recovery];else order=[catalog.upperPush,catalog.lower,catalog.upperPull,catalog.full,catalog.arms,catalog.recovery];if(goal==='Strength'&&focus!=='Bodyweight'){order=order.map(d=>({...d,ids:d.ids.filter(id=>!['fly','wrist','cablelatraise'].includes(id))}));}let used=[];for(let i=0;i<days;i++){let src=order[i%order.length];let ids=src.ids.filter(id=>E(id)).slice(0,slots);if(i>=order.length)ids=[...ids.slice(1),weak].filter((id,j,a)=>id&&E(id)&&a.indexOf(id)===j).slice(0,slots);used.push({name:src.name,note:src.note,ids});}return used}
function loadAdaptiveDay(i){let plan=window._adaptivePlan||adaptiveSplit(S.builder||{},bal().filter(x=>x.st==='Under').map(x=>x.m),bal().filter(x=>x.st==='High').map(x=>x.m));let d=plan[i];if(!d)return;S.w=make(d.ids,mem());S.e=0;S.rest=0;S.run=false;save();go('workout')}
function applyAdaptive(){loadAdaptiveDay(0)}
`;
s=s.slice(0,start)+repl+s.slice(end);
s=s.replace(/Peak Progress PWA v30 Workout Usability/g,'Peak Progress PWA v32 Adaptive Builder Pro');
s=s.replace(/v31/g,'v32').replace(/v30/g,'v32');
fs.writeFileSync('index.html',s);
